problemset: https://codeforces.com/api/problemset.problems

username: jaxleof
password: AIjiajia421

groupId: 9109
title: etst
announcement: miaomiao
beginTime: 2022-10-11 23:12:34
length: 5h12m
problems:
-   low: 800
    high: 1600
-   low: 1600
    high: 2000
-   low: 2000
    high: 2400