problemset: https://codeforces.com/api/problemset.problems

username: $vj_account
password: $vj_password

groupId: 
title: 
announcement: 
beginTime: 
length: 
problems:
-   low: 800
    high: 1600
-   low: 1600
    high: 2000
-   low: 2000
    high: 2400