problemset: https://codeforces.com/api/problemset.problems

username:
password: 

groupId: 9109
title: helloWerds
announcement: miaomiao
beginTime: 2022-06-12 23:12:34
length: 5h12m
problems:
-   low: 800
    high: 1600
-   low: 800
    high: 1600
-   low: 800
    high: 1600
-   low: 800
    high: 1600
-   low: 800
    high: 1600
-   low: 800
    high: 1600

